# name: Shorebird Patch

# on:
#   push

# jobs:
#   patch:
#     defaults:
#       run:
#         shell: bash

#     runs-on: ubuntu-latest

#     steps:
#       - name: 📚 Git Checkout
#         uses: actions/checkout@v3

#       - name: 🐦 Setup Shorebird
#         uses: shorebirdtech/setup-shorebird@v0

#       - name: 🚀 Shorebird Patch
#         run: shorebird patch android
#         env:
#           SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
